version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./databases/mongodb:/data/db

  mysql:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306
    volumes:
      - ./databases/mysql:/var/lib/mysql

  mariadb:
    image: mariadb:10.6.14
    environment:
      - MARIADB_ROOT_PASSWORD=5678
    ports:
      - 3305:3306
    volumes:
      - ./databases/mariadb:/var/lib/mysql

  my_express:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:3000
    environment:
      - MONGODB_HOST=mongodb

      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234

      - MARIADB_HOST=mariadb
      - MARIADB_USER=root
      - MARIADB_PASSWORD=5678
    volumes:
      - ./server:/servidor
      - /servidor/node_modules
